import React from 'react';
import { View } from 'react-native';
import { Avatar, ScrollView } from 'native-base';

export default function scrollServices() {
 return (
    <ScrollView
    showsHorizontalScrollIndicator={false}
    py="2"
    px="5"
    horizontal={true}
    w="100%"
    t="0"
    h="30%"
  >
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/cord-administrativa.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/cord-voluntarios.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-cidadania.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-mulher.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-reforcoescolar.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-autistas.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-cursos.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-enem.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-optometria.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-saudemental.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-sgralimentar.jpg")}
    />
    <Avatar
      mx="1"
      size="2xl"
      shadow={3}
      source={require("../../assets/imgs/pip-protagonista.jpg")}
    />
  </ScrollView>
  );
}